import React from 'react';

export default function HowZytoWorks() {
  return (
    <div style={{ marginTop: 40, lineHeight: 1.7, maxWidth: 900 }}>
      <h2>⚙️ How ZYTO Measures Wellness</h2>
      <p>
        Using GSR (Galvanic Skin Response) data from the ZYTO Hand Cradle, the Balance software runs automated biosurveys and evaluates responses to Virtual Items such as:
      </p>
      <ul>
        <li>🧬 Organs, Hormones, Chemicals</li>
        <li>🌿 Nutritional supplements & essential oils</li>
        <li>🏥 Clinical or referred wellness services</li>
      </ul>
      <p>
        Reports generated by ZYTO help wellness professionals and their clients make more targeted and personalized health decisions.
      </p>
    </div>
  );
}
