import React, { useState } from 'react';
import Navbar from '../components/Navbar';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const images = [
    'Messenger_creation_4F759699-F60C-4ABE-BE29-5C1532358AEB.jpeg',
    'Messenger_creation_A5E20197-3662-47DE-821C-A8E698AF7431.jpeg',
    'received_1224910739346831.jpeg',
    'received_1457436602288731.jpeg',
    'received_1934050417398656.jpeg',
    'received_2214373082353312.jpeg',
    'received_691148193771669.jpeg',
    'received_710740961547251.jpeg',
    'received_9828388613863441.jpeg'
  ];

  const styles = {
    page: {
      fontFamily: 'sans-serif',
      padding: '80px 40px 60px',
      minHeight: '100vh',
      color: darkMode ? '#E3F2FD' : '#0D47A1',
      background: darkMode
        ? 'linear-gradient(to bottom right, #0d1b2a, #1b263b, #415a77)'
        : 'linear-gradient(to bottom right, #e3f2fd, #ffffff)',
      transition: 'all 0.3s ease'
    },
    navbar: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      height: 60,
      backgroundColor: darkMode ? '#0b0f2c' : '#ffffff',
      color: darkMode ? '#BBDEFB' : '#0D47A1',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '0 30px',
      boxShadow: '0 4px 20px rgba(13, 71, 161, 0.4)',
      zIndex: 1000
    },
    button: {
      padding: '10px 18px',
      borderRadius: 8,
      background: darkMode
        ? 'linear-gradient(45deg, #2196f3, #1e88e5)'
        : 'linear-gradient(45deg, #64b5f6, #1976d2)',
      color: '#fff',
      border: 'none',
      fontWeight: 'bold',
      cursor: 'pointer'
    },
    section: {
      marginTop: 40,
      lineHeight: 1.7,
      maxWidth: 900
    },
    img: {
      width: '100%',
      borderRadius: 12,
      boxShadow: '0 8px 16px rgba(13, 71, 161, 0.5)',
      transition: 'transform 0.3s ease'
    },
    facebookButton: {
      display: 'inline-block',
      marginTop: 40,
      padding: '14px 28px',
      background: 'linear-gradient(to right, #00c6ff, #0072ff)',
      color: 'white',
      borderRadius: 10,
      textDecoration: 'none',
      fontWeight: 'bold',
      boxShadow: '0 6px 16px rgba(0, 0, 0, 0.4)'
    }
  };

  return (
    <div style={styles.page}>
      {/* Navbar */}
      <div style={styles.navbar}>
        <h2>Zyto Scan</h2>
        <button style={styles.button} onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? '🌙 Dark Mode' : '☀️ Light Mode'}
        </button>
      </div>

      {/* Welcome Section */}
      <h1>🌈 Welcome to ZYTO Scanning</h1>
      <p>Empowering personalized wellness through bio-communication technology.</p>

      {/* What is ZYTO Scan */}
      <div style={styles.section}>
        <h2>🔍 What is ZYTO?</h2>
        <p>
          The ZYTO software combines top product preferences with key body and lifestyle data from 190+ biomarkers to help you make informed wellness decisions.
        </p>
        <ul>
          <li>✅ Personalized supplement & essential oil suggestions</li>
          <li>✅ Emotional health tools via neurofeedback</li>
          <li>✅ Food biosurveys for better dietary decisions</li>
          <li>✅ Generate future appointments for clients</li>
        </ul>
      </div>

      {/* How ZYTO Works */}
      <div style={styles.section}>
        <h2>⚙️ How ZYTO Measures Wellness</h2>
        <p>
          Using GSR (Galvanic Skin Response) data from the ZYTO Hand Cradle, the Balance software runs automated biosurveys and evaluates responses to Virtual Items such as:
        </p>
        <ul>
          <li>🧬 Organs, Hormones, Chemicals</li>
          <li>🌿 Nutritional supplements & essential oils</li>
          <li>🏥 Clinical or referred wellness services</li>
        </ul>
        <p>
          Reports generated by ZYTO help wellness professionals and their clients make more targeted and personalized health decisions.
        </p>
      </div>

      {/* Emotional Wellness Section */}
      <div style={styles.section}>
        <h2>🧠 Improve Emotional Wellness</h2>
        <p>
          ZYTO’s Perception Reframing uses voice-mapped neurofeedback to detect subconscious emotional patterns and help reframe negative perceptions—enhancing emotional well-being effectively.
        </p>
      </div>

      {/* Image Gallery */}
      <div style={styles.section}>
        <h2>🖼️ ZYTO Scanning Image Gallery</h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
          gap: 20,
          marginTop: 20
        }}>
          {images.map((img, index) => (
            <img
              key={index}
              src={`/images/${img}`}
              alt={`Image ${index + 1}`}
              style={styles.img}
              onMouseOver={e => (e.currentTarget.style.transform = 'scale(1.05)')}
              onMouseOut={e => (e.currentTarget.style.transform = 'scale(1)')}
            />
          ))}
        </div>
{/* Video Section */}
<div style={styles.section}>
  <h2>🎥 ZYTO Scan Overview Video</h2>
  <div style={{
    position: 'relative',
    paddingBottom: '56.25%',
    paddingTop: 25,
    height: 0,
    overflow: 'hidden',
    borderRadius: 12,
    boxShadow: '0 8px 16px rgba(13, 71, 161, 0.5)'
  }}>
    <iframe
      src="https://www.youtube.com/embed/dFNnGsnMZxc"
      title="ZYTO Scan Overview"
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        border: '0',
        borderRadius: '12px'
      }}
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowFullScreen
    ></iframe>
  </div>
</div>
          
      </div>

      {/* Facebook Button */}
      <a
        href="https://www.facebook.com/joreen.torno.3"
        target="_blank"
        rel="noopener noreferrer"
        style={styles.facebookButton}
      >
        🔗 Visit My Facebook
      </a>

      {/* Disclaimer */}
      <div style={{ ...styles.section, fontSize: '0.9em', color: darkMode ? '#B0BEC5' : '#455A64' }}>
        <h3>⚠️ Disclaimer</h3>
        <p>
          The ZYTO Balance software and content provided are intended for informational purposes only and are not substitutes for medical advice, diagnosis, or treatment. Always consult a qualified health provider before making decisions regarding wellness. Individual results may vary.
        </p>
      </div>
    </div>
  );
    }
